# Generated by Django 4.2.7 on 2023-11-17 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0003_alter_list_name_card"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card",
            old_name="description",
            new_name="content",
        ),
    ]
