# Generated by Django 4.2.7 on 2023-11-17 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0004_rename_description_card_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card",
            old_name="list",
            new_name="columnId",
        ),
    ]
