# Generated by Django 4.2.7 on 2023-11-17 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0005_rename_list_card_columnid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="list",
            old_name="name",
            new_name="title",
        ),
    ]
